export const GET_PATIENT_DATA = "GET_PATIENT_DATA";
export const GET_PATIENT_DATA_SUCCESS = "GET_PATIENT_DATA_SUCCESS";

export const LOGIN_AS_PATIENT = "LOGIN_AS_PATIENT";
export const LOGIN_AS_PATIENT_SUCCESS = "LOGIN_AS_PATIENT_SUCCESS";
export const REGISTER_AS_PATIENT = "REGISTER_AS_PATIENT";
export const REGISTER_AS_PATIENT_SUCCESS = "REGISTER_AS_PATIENT_SUCCESS";

export const UPDATE_PATIENT_DATA = "UPDATE_PATIENT_DATA";
export const UPDATE_PATIENT_DATA_SUCCESS = "UPDATE_PATIENT_DATA_SUCCESS";

export const UPDATE_PATIENT_REPORTS = "UPDATE_PATIENT_REPORTS";
export const DELETE_PATIENT_REPORTS = "DELETE_PATIENT_REPORTS";

export const GET_PATIENT_DOCTORS_EXPLORE_DATA = "GET_PATIENT_DOCTORS_EXPLORE_DATA";
export const GET_PATIENT_DOCTORS_EXPLORE_DATA_SUCCESS = "GET_PATIENT_DOCTORS_EXPLORE_DATA_SUCCESS";

export const UPDATE_NEW_CHAT_WITH_DOCTOR = "UPDATE_NEW_CHAT_WITH_DOCTOR";
export const UPDATE_NEW_CHAT_WITH_DOCTOR_SUCCESS = "UPDATE_NEW_CHAT_WITH_DOCTOR_SUCCESS";

export const GET_PATIENT_MESSAGE_LIST = "GET_PATIENT_MESSAGE_LIST";
export const GET_PATIENT_MESSAGE_LIST_SUCCESS = "GET_PATIENT_MESSAGE_LIST_SUCCESS";


// -----------------------------
// -----------------------------


export const GET_DOCTOR_DATA = "GET_DOCOTR_DATA";
export const GET_DOCTOR_DATA_SUCCESS = "GET_DOCOTR_DATA_SUCCESS";

export const LOGIN_AS_DOCTOR = "LOGIN_AS_DOCTOR";
export const LOGIN_AS_DOCTOR_SUCCESS = "LOGIN_AS_DOCTOR_SUCCESS";
export const REGISTER_AS_DOCTOR = "REGISTER_AS_DOCTOR";
export const REGISTER_AS_DOCTOR_SUCCESS = "REGISTER_AS_DOCTOR_SUCCESS";

export const UPDATE_DOCTOR_DATA = "UPDATE_DOCTOR_DATA";
export const UPDATE_DOCTOR_DATA_SUCCESS = "UPDATE_DOCTOR_DATA_SUCCESS";

export const GET_DOCTOR_MESSAGE_LIST = "GET_DOCTOR_MESSAGE_LIST";
export const GET_DOCTOR_MESSAGE_LIST_SUCCESS = "GET_DOCTOR_MESSAGE_LIST_SUCCESS";


export const GET_USER_CHATS = "GET_USER_CHATS";

// -----------------------------
// -----------------------------

export const UPDATE_DOCTOR_PATIENT_APPOINTMENT = "UPDATE_DOCTOR_PATIENT_APPOINTMENT";
